sudo: required
services:
  - docker

before_install:
  - docker build -t gohan01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gohan01/react-test npm test

after_success:
  - docker build -t gohan01/multi-client ./client
  - docker build -t gohan01/multi-nginx ./nginx
  - docker build -t gohan01/multi-server ./server
  - docker build -t gohan01/multi-worker ./worker
  # Login into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push gohan01/multi-client
  - docker push gohan01/multi-nginx
  - docker push gohan01/multi-server
  - docker push gohan01/multi-worker
